# env vars

shopt -s globstar

export ORACLE_HOME=/usr/lib/oracle/11.2/client64
export LD_LIBRARY_PATH=$ORACLE_HOME/lib

PPIT_ROOT=/home/spi/dev/ppit
export SPP_HOME=/home/spi/.spp
export ECLIPSE_WORKSPACE=/home/spi/workspace
export PPIT_CHECK_TEST_DB_CLEANUP=1
export JAVA_HOME="/usr/lib/jvm/java-6-oracle"
export VAGRANT_USE_NO_NFS="true"
export EDITOR=vim
export BROWSER=google-chrome
# export VAGRANT_DEBUG="true"

. $SPP_HOME/gee/src/gee.sh

# # commit current task with a provided message
# function .gitCommit() {
#     message="$*"
#     cmd="git commit -m \"$(cat $JIRA_TICKET_PATH) $message\""
#     read -p "commit: $cmd [Y/n] " yn
#     case $yn in
#         [Nn]* ) return;;
#         * ) eval $cmd; return;;
#     esac
# }
 alias .review="chrome /home/spi/dev/review/index.html"
# 
# 
# # alias checkstyle="checkstyle -c ~/.checkstyle/tng_checks.xml"
# alias pmd="/home/spi/dev/utils/pmd-bin-5.1.3/bin/run.sh pmd"
# alias cpd="/home/spi/dev/utils/pmd-bin-5.1.3/bin/run.sh cpd"

# aliases for edit a configuration
alias .bashrcEdit="vim $SPP_HOME/bash/bashrc"
alias .bashrcSource=". $HOME/.bashrc"
alias .vimEdit="vim $SPP_HOME/vim/"

# aliases for change a directory
alias .cd="cd $PPIT_ROOT"
alias .cd.database="cd $PPIT_ROOT/database"

# set -o vi
alias xclip='xclip -selection clipboard'

# show git current branch in a bash prompt
export PS1='$(__git_ps1) \W\$ '

#. $SPP_HOME/bash/git-completion.bash
. /var/lib/gems/1.9.1/gems/tmuxinator-0.6.8/completion/tmuxinator.bash

#GRADLE_HOME=/opt/gradle-2.1
#export PATH=$PATH:$GRADLE_HOME/bin
